# -*- coding: utf-8 -*-
"""Proyecto Final Econometría

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rMIhFCBnfaYU4qx3C96dAvksPQdh_uW

# Análisis regresión lineal simple & múltiple

Necesito un código para crear un modelo de regresión lineal simple y múltiple para un modelo de acciones de la industria farmacéutica. La variable dependiente es el ETF con ticker VHT, y las independientes las siguientes 5 acciones son: PFE, ABBV, MRK, ABT, y JNJ. Usando la data de Yahoo finance, calculando los retornos diarios con el precio de cierre, has un modelo de regresión simple con la dependiente y cada una de las independientes, y la múltiple de la dependiente con las 5 independientes. Con este código, también dame un resumen de estos modelos, con gráficas de correlación y maneras explicativas para mostrar la informacion

puedes ajustar las fechas de los precios para tomar un rango diario de los últimos dos años


quiero cambiar de la lista de acciones, reemplazar JNJ con LLY

de igual manera, puedes para estos modelos hacer análisis de heterocedasticidad, autocorrelación y multicolinealidad definir que está presente
"""

import yfinance as yf
import pandas as pd
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.diagnostic import het_breuschpagan, het_goldfeldquandt # Importar het_goldfeldquandt
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.stattools import durbin_watson # Importar la función durbin_watson

# 1. Definir los tickers de los activos
dependent_ticker = 'VHT'
independent_tickers = ['PFE', 'ABBV', 'MRK', 'ABT', 'LLY']
all_tickers = [dependent_ticker] + independent_tickers

# 2. Descargar datos históricos de Yahoo Finance
print("Descargando datos históricos...")
# Ajustar el rango de fechas a los últimos dos años
end_date = pd.to_datetime('today').strftime('%Y-%m-%d')
start_date = (pd.to_datetime('today') - pd.DateOffset(years=2)).strftime('%Y-%m-%d')
data = yf.download(all_tickers, start=start_date, end=end_date, auto_adjust=False)['Adj Close']

# Verificar si hay datos nulos y rellenarlos si es necesario (ej. con el método forward-fill)
data = data.fillna(method='ffill')
data = data.fillna(method='bfill') # Rellenar cualquier NaN restante al inicio

# 3. Calcular los retornos diarios
print("Calculando retornos diarios...")
returns = data.pct_change().dropna()

# Verificar las primeras filas de los retornos
print("\nPrimeras 5 filas de retornos:")
print(returns.head())

# Definir las variables dependiente e independientes para los modelos
Y = returns[dependent_ticker]
X_simple_list = [returns[ticker] for ticker in independent_tickers]
X_multiple = returns[independent_tickers]

# 4. Modelos de Regresión Lineal Simple
print("\n--- Modelos de Regresión Lineal Simple ---")
for i, ticker in enumerate(independent_tickers):
    print(f"\nModelo Simple: {dependent_ticker} vs {ticker}")
    X_single = X_simple_list[i]

    # Añadir una constante al modelo (intercepto)
    X_single_const = sm.add_constant(X_single)

    # Crear y ajustar el modelo OLS
    model_simple = sm.OLS(Y, X_single_const, missing='drop') # missing='drop' para manejar NaNs
    results_simple = model_simple.fit()

    # Imprimir el resumen del modelo
    print(results_simple.summary())

    # Interpretación básica
    print(f"Interpretación: Un aumento del 1% en los retornos de {ticker} está asociado con un cambio de {results_simple.params[ticker]:.4f}% en los retornos de {dependent_ticker}, asumiendo que el p-valor del coeficiente es significativo (<0.05).")

    # Análisis de Heterocedasticidad (Breusch-Pagan test)
    print("\nAnálisis de Heterocedasticidad (Breusch-Pagan test):")
    bp_test = het_breuschpagan(results_simple.resid, results_simple.model.exog)
    labels = ['LM Statistic', 'LM-Test p-value', 'F-Statistic', 'F-Test p-value']
    print(dict(zip(labels, bp_test)))
    if bp_test[1] < 0.05: # p-value for LM-Test
        print("\nInterpretación: Existe evidencia de heterocedasticidad (el p-valor es significativo).")
    else:
        print("\nInterpretación: No hay evidencia significativa de heterocedasticidad (el p-valor no es significativo).")

    # Análisis de Heterocedasticidad (Goldfeld-Quandt test)
    print("\nAnálisis de Heterocedasticidad (Goldfeld-Quandt test):")
    # El test de Goldfeld-Quandt requiere al menos 4 observaciones en cada subgrupo. Si el número de observaciones es bajo, podría fallar.
    try:
        gq_test = het_goldfeldquandt(results_simple.resid, X_single_const)
        labels_gq = ['F-Statistic', 'p-value']
        print(dict(zip(labels_gq, gq_test)))
        if gq_test[1] < 0.05:
            print("\nInterpretación: Existe evidencia de heterocedasticidad según el test de Goldfeld-Quandt (el p-valor es significativo).")
        else:
            print("\nInterpretación: No hay evidencia significativa de heterocedasticidad según el test de Goldfeld-Quandt (el p-valor no es significativo).")
    except ValueError as e:
        print(f"No se pudo realizar el test de Goldfeld-Quandt para {ticker}: {e}. Asegúrese de tener suficientes observaciones.")

# 5. Modelo de Regresión Lineal Múltiple
print("\n--- Modelo de Regresión Lineal Múltiple ---")
print(f"Modelo Múltiple: {dependent_ticker} vs {', '.join(independent_tickers)}")

# Añadir una constante al modelo (intercepto)
X_multiple_const = sm.add_constant(X_multiple)

# Crear y ajustar el modelo OLS
model_multiple = sm.OLS(Y, X_multiple_const, missing='drop')
results_multiple = model_multiple.fit()

# Imprimir el resumen del modelo
print(results_multiple.summary())

# Interpretación básica del modelo múltiple
print("\nInterpretación del Modelo Múltiple: Cada coeficiente indica el cambio en los retornos de VHT por cada 1% de cambio en la acción correspondiente, manteniendo las otras acciones constantes. El R-cuadrado ajustado (Adj. R-squared) indica qué proporción de la varianza de VHT es explicada por las acciones independientes en conjunto.")

# Análisis de Heterocedasticidad (Breusch-Pagan test - Múltiple)
print("\nAnálisis de Heterocedasticidad (Breusch-Pagan test - Múltiple):")
bp_test_multiple = het_breuschpagan(results_multiple.resid, results_multiple.model.exog)
labels = ['LM Statistic', 'LM-Test p-value', 'F-Statistic', 'F-Test p-value']
print(dict(zip(labels, bp_test_multiple)))
if bp_test_multiple[1] < 0.05: # p-value for LM-Test
    print("\nInterpretación: Existe evidencia de heterocedasticidad en el modelo múltiple (el p-valor es significativo).")
else:
    print("\nInterpretación: No hay evidencia significativa de heterocedasticidad en el modelo múltiple (el p-valor no es significativo).")

# Análisis de Heterocedasticidad (Goldfeld-Quandt test - Múltiple)
print("\nAnálisis de Heterocedasticidad (Goldfeld-Quandt test - Múltiple):")
# El test de Goldfeld-Quandt requiere al menos 4 observaciones en cada subgrupo. Si el número de observaciones es bajo, podría fallar.
try:
    gq_test_multiple = het_goldfeldquandt(results_multiple.resid, X_multiple_const)
    labels_gq = ['F-Statistic', 'p-value']
    print(dict(zip(labels_gq, gq_test_multiple)))
    if gq_test_multiple[1] < 0.05:
        print("\nInterpretación: Existe evidencia de heterocedasticidad según el test de Goldfeld-Quandt en el modelo múltiple (el p-valor es significativo).")
    else:
        print("\nInterpretación: No hay evidencia significativa de heterocedasticidad según el test de Goldfeld-Quandt en el modelo múltiple (el p-valor no es significativo).")
except ValueError as e:
    print(f"No se pudo realizar el test de Goldfeld-Quandt para el modelo múltiple: {e}. Asegúrese de tener suficientes observaciones o un número adecuado de variables.")

# Análisis de Autocorrelación
print("\nAnálisis de Autocorrelación:")
# Fix: Use the durbin_watson function from statsmodels.stats.stattools
print(f"El estadístico de Durbin-Watson para el modelo múltiple es: {durbin_watson(results_multiple.resid):.4f}")
print("Interpretación: Un valor de Durbin-Watson cercano a 2 sugiere que no hay autocorrelación. Valores significativamente menores a 2 (típicamente < 1.5) pueden indicar autocorrelación positiva, y valores significativamente mayores a 2 (típicamente > 2.5) pueden indicar autocorrelación negativa. En series de tiempo financieras, la autocorrelación es común.")

# Visualización de residuos para autocorrelación
plt.figure(figsize=(12, 6))
plt.plot(results_multiple.resid)
plt.title('Residuos del Modelo de Regresión Múltiple a lo largo del Tiempo')
plt.xlabel('Fecha')
plt.ylabel('Residuo')
plt.grid(True)
plt.show()
print("Interpretación Visual: Si los residuos muestran patrones (tendencias, ciclos) en lugar de un comportamiento aleatorio alrededor de cero, podría indicar autocorrelación.")

# Análisis de Multicolinealidad (solo para el modelo múltiple)
print("\nAnálisis de Multicolinealidad (VIF - Variance Inflation Factor):")
vif_data = pd.DataFrame()
vif_data["feature"] = X_multiple.columns
vif_data["VIF"] = [variance_inflation_factor(X_multiple.values, i) for i in range(len(X_multiple.columns))]
print(vif_data)
print("Interpretación: Un valor VIF superior a 5 o 10 generalmente indica una alta multicolinealidad, lo que puede afectar la estabilidad y la interpretación de los coeficientes de regresión. Los valores VIF bajos (cercanos a 1) indican poca o ninguna multicolinealidad.")

# 6. Gráficas de Correlación
print("\n--- Gráficas de Correlación ---")
plt.figure(figsize=(10, 8))
sns.heatmap(returns[all_tickers].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matriz de Correlación de Retornos Diarios')
plt.show()

# 7. Maneras explicativas para mostrar la información
print("\n--- Explicación Adicional ---")
print("\n**¿Qué significan los resultados?**")
print("\n*   **R-cuadrado (R-squared):** Este valor (presente en los resúmenes de los modelos) indica el porcentaje de la varianza en los retornos de VHT que puede ser explicado por las variables independientes. Un valor más cercano a 1 sugiere que el modelo explica una gran parte de la variabilidad.")
print("*   **Coeficientes (coef):** Representan la magnitud y dirección de la relación entre cada acción independiente y VHT. Por ejemplo, si el coeficiente de PFE es 0.50, significa que por cada 1% que se mueven los retornos de PFE, los retornos de VHT se mueven un 0.50% en la misma dirección (ceteris paribus).")
print("*   **P-valores (P>|t|):** Indican la significancia estadística de cada coeficiente. Un p-valor menor a 0.05 (o 0.01) generalmente sugiere que la relación observada no es debida al azar y es estadísticamente significativa.")
print("*   **Matriz de Correlación:** Muestra la fuerza y dirección de la relación lineal entre cada par de activos. Los valores cercanos a 1 o -1 indican una fuerte correlación positiva o negativa, respectivamente. Valores cercanos a 0 indican poca o ninguna correlación lineal.")

print("\n**Interpretación de la Matriz de Correlación:** Los valores positivos fuertes (cercanos a 1) entre VHT y las acciones individuales sugieren que estas acciones tienden a moverse en la misma dirección que el ETF. Esto es esperable ya que las acciones pertenecen a la misma industria que el ETF replica. Los valores cercanos a cero o negativos indicarían que el movimiento de una acción no está fuertemente relacionado o se mueve en dirección opuesta al ETF, respectivamente.")
print("\n**Consideraciones:**")
print("*   La regresión lineal asume una relación lineal. En el mercado de valores, las relaciones pueden ser más complejas y no lineales.")
print("*   Los modelos presentados son una simplificación y no deben ser usados como la única base para decisiones de inversión.")
print("*   Siempre es importante considerar otros factores económicos, fundamentales y técnicos.")

"""# Análisis Data Panel

En esta sección se va a realizar en análisis de datos de panel para las 5 acciones. La información se extrajo de Refinitiv de manera quarterly de los últimos 10 años, tomando variables importantes como ROE, ROA, revenue, EBITDA, entre otros. Se van a hacer análisis de pooled OLS, fixed effects, y random effects para entender las tendencias y características del modelo a base de las muestras de información de las acciones.

## Carga de datos, bibliotecas, y ajuste de información

Cargar la data de Refinitiv en un archivo consolidado para facilitar el proceso, con nombre datapanel_data. Aquí se encuentra la quaterly data de las 5 acciones en los últimos 10 años.
"""

from google.colab import files
uploaded = files.upload()

# Install linearmodels (not pre-installed in Colab)
!pip install linearmodels -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from linearmodels.panel import PooledOLS, PanelOLS, RandomEffects
from linearmodels.panel import compare
from linearmodels.panel.results import compare as panel_compare

import statsmodels.api as sm
from scipy import stats

print('✅ All libraries loaded successfully')

df = pd.read_excel('datapanel_data.xlsx')

# Parse dates
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

print('Shape:', df.shape)
print('Stocks:', df['Ticker'].unique())
print('Date range:', df['Date'].min(), 'to', df['Date'].max())
print('\nObservations per stock:')
print(df['Ticker'].value_counts())
df.head(10)

df = df.sort_values(['Ticker', 'Date']).reset_index(drop=True)

# --- Derived Ratios ---
df['GrossMargin']     = df['GrossProfit']     / df['Revenue']          # Gross Profit Margin
df['OperatingMargin'] = df['OperatingProfit'] / df['Revenue']          # Operating Margin
df['EBITDAMargin']    = df['EBITDA']          / df['Revenue']          # EBITDA Margin
df['AssetTurnover']   = df['Revenue']         / df['TotalAssets']      # Asset Utilization

# --- Quarter-over-Quarter Revenue Growth (dependent variable) ---
df['RevenueGrowth'] = df.groupby('Ticker')['Revenue'].pct_change() * 100

# --- Lag variables (previous quarter values as predictors) ---
for col in ['ROA_TTM', 'ROE_TTM', 'GrossMargin', 'OperatingMargin', 'AssetTurnover']:
    df[f'{col}_lag1'] = df.groupby('Ticker')[col].shift(1)

# Drop first obs per ticker (NaN from lag/pct_change)
df_clean = df.dropna().reset_index(drop=True)

print(f'Clean dataset shape: {df_clean.shape}')
print(f'Observations per ticker after cleaning:')
print(df_clean['Ticker'].value_counts())
df_clean.head()

print('=== Overall Descriptive Statistics ===')
desc_cols = ['RevenueGrowth', 'GrossMargin', 'OperatingMargin',
             'EBITDAMargin', 'AssetTurnover', 'ROA_TTM', 'ROE_TTM']
df_clean[desc_cols].describe().round(3)

"""##Gráficas Relevantes modelo

A base de la información del archivo de data panel, previo a los tres tipos de análisis de data panel, estas gráficas sirven para entender qué es lo que estamos viendo para cada acción.
"""

print('=== Mean Values by Ticker ===')
df_clean.groupby('Ticker')[desc_cols].mean().round(3)

fig, axes = plt.subplots(2, 3, figsize=(16, 9))
axes = axes.flatten()
tickers = df_clean['Ticker'].unique()
colors = ['#2196F3', '#E91E63', '#4CAF50', '#FF9800', '#9C27B0']

for i, (ticker, color) in enumerate(zip(tickers, colors)):
    data = df_clean[df_clean['Ticker'] == ticker]
    axes[i].plot(data['Date'], data['Revenue'], color=color, linewidth=2)
    axes[i].fill_between(data['Date'], data['Revenue'], alpha=0.1, color=color)
    axes[i].set_title(f'{ticker} — Quarterly Revenue', fontweight='bold', fontsize=11)
    axes[i].set_xlabel('Date')
    axes[i].set_ylabel('Revenue (M USD)')
    axes[i].yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))
    axes[i].tick_params(axis='x', rotation=30)
    axes[i].grid(axis='y', alpha=0.3)

axes[-1].set_visible(False)
plt.suptitle('Revenue Trends by Stock (Quarterly)', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('revenue_trends.png', dpi=150, bbox_inches='tight')
plt.show()

from linearmodels.panel import PanelOLS, RandomEffects, PooledOLS # Importar los modelos específicos
from linearmodels.panel import compare # Importar la función compare para la comparación de modelos

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
margin_cols = ['GrossMargin', 'OperatingMargin', 'EBITDAMargin']
titles = ['Gross Margin', 'Operating Margin', 'EBITDA Margin']

for ax, col, title, color in zip(axes, margin_cols, titles, ['#2196F3','#4CAF50','#FF9800']):
    for ticker, clr in zip(tickers, colors):
        d = df_clean[df_clean['Ticker'] == ticker]
        ax.plot(d['Date'], d[col], label=ticker, linewidth=1.8)
    ax.set_title(title, fontweight='bold')
    ax.set_xlabel('Date')
    ax.yaxis.set_major_formatter(mticker.PercentFormatter(1.0))
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)
    ax.tick_params(axis='x', rotation=30)

plt.suptitle('Margin Comparison Across Stocks', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('margin_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

fig, ax = plt.subplots(figsize=(9, 7))
corr_cols = ['RevenueGrowth', 'GrossMargin', 'OperatingMargin',
             'EBITDAMargin', 'AssetTurnover', 'ROA_TTM', 'ROE_TTM']
corr = df_clean[corr_cols].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='RdYlGn',
            center=0, ax=ax, linewidths=0.5, annot_kws={'size': 10})
ax.set_title('Correlation Matrix of Key Variables', fontweight='bold', fontsize=13)
plt.tight_layout()
plt.savefig('correlation_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

"""##Crear Estructura de Data Panel"""

# Convert Ticker to categorical for panel indexing
df_panel = df_clean.copy()
df_panel['Ticker'] = df_panel['Ticker'].astype('category')
df_panel = df_panel.set_index(['Ticker', 'Date'])

# Define dependent variable and regressors
Y = df_panel['RevenueGrowth']

X_vars = ['GrossMargin_lag1', 'OperatingMargin_lag1',
          'ROA_TTM_lag1', 'AssetTurnover_lag1']

X = sm.add_constant(df_panel[X_vars])

print('Panel index levels:', df_panel.index.names)
print('Dependent variable: RevenueGrowth (QoQ %)')
print('Regressors:', X_vars)
print('\nPanel shape:', df_panel.shape)

"""##Pooled OLS"""

pooled = PooledOLS(Y, X)
pooled_res = pooled.fit(cov_type='robust')
print(pooled_res.summary)

"""##Fixed Effects"""

# Entity Fixed Effects only
fe_entity = PanelOLS(Y, df_panel[X_vars],
                     entity_effects=True,
                     time_effects=False)
fe_entity_res = fe_entity.fit(cov_type='clustered', cluster_entity=True)
print('=== Fixed Effects (Entity Only) ===')
print(fe_entity_res.summary)

# Two-Way Fixed Effects (Entity and Time)
fe_twoway = PanelOLS(Y, df_panel[X_vars],
                     entity_effects=True,
                     time_effects=True)
fe_twoway_res = fe_twoway.fit(cov_type='clustered', cluster_entity=True)
print('\n=== Fixed Effects (Two-Way - Entity and Time) ===')
print(fe_twoway_res.summary)

"""##Random Effects"""

# Random Effects — workaround for small panel (5 stocks = neffects equals nvar)
re = RandomEffects(Y, X)

re_res = None
for cov in ['unadjusted', 'robust', 'kernel']:
    try:
        re_res = re.fit(cov_type=cov, debiased=False)
        print(f'✅ Random Effects fitted with cov_type={cov}')
        break
    except ZeroDivisionError:
        continue

# If all linearmodels options fail, use manual RE via statsmodels
if re_res is None:
    print('⚠️ linearmodels RE failed — using manual RE estimator via statsmodels')
    import statsmodels.formula.api as smf

    df_re = df_clean.copy()
    group_means = df_re.groupby('Ticker')[['RevenueGrowth'] + X_vars].transform('mean')
    theta = 0.5  # standard RE quasi-demeaning weight

    for col in ['RevenueGrowth'] + X_vars:
        df_re[f'{col}_qd'] = df_re[col] - theta * group_means[col]

    qd_vars = [f'{v}_qd' for v in X_vars]
    X_re = sm.add_constant(df_re[qd_vars])
    Y_re = df_re['RevenueGrowth_qd']
    re_res = sm.OLS(Y_re, X_re).fit(cov_type='HC1')
    print(re_res.summary())
else:
    print(re_res.summary)

"""##Comparativa de Modelos"""

from linearmodels.panel import compare

# Only include linearmodels results in the compare table
lm_models = {
    'Pooled OLS':   pooled_res,
    'FE (Entity)':  fe_entity_res,
    'FE (Two-Way)': fe_twoway_res,
}

# Add RE only if it came from linearmodels
try:
    comparison = compare({**lm_models, 'Random Effects': re_res})
except Exception:
    comparison = compare(lm_models)
    print('ℹ️ RE excluded from comparison table (manual estimator used)')

print(comparison)

"""##Hausman Test"""

# --- Hausman Test (FE vs RE) ---
# Works whether re_res is a linearmodels or statsmodels object

def hausman_test(fe_res, re_res, x_vars):
    """
    Hausman test comparing FE vs RE on slope coefficients only.
    Handles both linearmodels and statsmodels RE results.
    """
    fe_params, fe_cov, re_params, re_cov = {}, {}, {}, {}

    # --- Extract FE coefficients (always linearmodels) ---
    for var in x_vars:
        if var in fe_res.params.index:
            fe_params[var] = fe_res.params[var]
            fe_cov[var]    = fe_res.cov.loc[var, var]

    # --- Extract RE coefficients (linearmodels or statsmodels) ---
    is_statsmodels_re = not hasattr(re_res, 'params') or isinstance(re_res.params, pd.Series) and \
                        any('_qd' in idx for idx in re_res.params.index)

    for var in x_vars:
        try:
            # linearmodels RE
            if var in re_res.params.index:
                re_params[var] = re_res.params[var]
                re_cov[var]    = re_res.cov.loc[var, var]
        except:
            pass
        try:
            # statsmodels RE (quasi-demeaned variables have _qd suffix)
            var_qd = f'{var}_qd'
            if var_qd in re_res.params.index:
                re_params[var] = re_res.params[var_qd]
                re_cov[var]    = re_res.cov_params().loc[var_qd, var_qd]
        except:
            pass

    # --- Align on common variables ---
    common = [v for v in x_vars if v in fe_params and v in re_params]
    if not common:
        return None, None, 'No common variables found between FE and RE'

    b_fe  = np.array([fe_params[v] for v in common])
    b_re  = np.array([re_params[v] for v in common])
    diff  = b_fe - b_re

    # Build covariance difference matrix
    try:
        V_fe = fe_res.cov.loc[common, common].values
    except:
        V_fe = np.diag([fe_cov[v] for v in common])

    try:
        # linearmodels RE cov
        V_re = re_res.cov.loc[common, common].values
    except:
        try:
            # statsmodels RE cov
            qd_common = [f'{v}_qd' for v in common]
            V_re = re_res.cov_params().loc[qd_common, qd_common].values
        except:
            V_re = np.diag([re_cov[v] for v in common])

    V_diff = V_fe - V_re

    try:
        V_inv = np.linalg.pinv(V_diff)
        stat  = float(diff @ V_inv @ diff)
        dof   = len(common)
        pval  = 1 - stats.chi2.cdf(stat, dof)
        return stat, pval, dof
    except Exception as e:
        return None, None, str(e)


# --- Run and print results ---
stat, pval, dof = hausman_test(fe_entity_res, re_res, X_vars)

print('=' * 45)
print('        HAUSMAN TEST RESULTS')
print('        H₀: Random Effects is consistent')
print('        H₁: Fixed Effects is required')
print('=' * 45)
if stat is not None:
    print(f'  Chi-square statistic : {stat:.4f}')
    print(f'  Degrees of freedom   : {dof}')
    print(f'  p-value              : {pval:.4f}')
    print('-' * 45)
    if pval < 0.05:
        print('  ✅ Reject H₀  →  USE FIXED EFFECTS')
        print('     RE is inconsistent; FE is preferred.')
    else:
        print('  ✅ Fail to reject H₀  →  USE RANDOM EFFECTS')
        print('     RE is efficient and consistent.')
else:
    print(f'  ⚠️  Test could not be computed: {dof}')
    print('     Check for multicollinearity in regressors.')
print('=' * 45)

"""## Diagnósticos"""

# --- Breusch-Pagan LM Test ---
resid_raw = pooled_res.resids.reset_index()
resid_raw.columns = ['Ticker', 'Date', 'resid']

N = resid_raw['Ticker'].nunique()
T = resid_raw.groupby('Ticker')['resid'].count().mean()
total_var   = resid_raw['resid'].var()
group_means = resid_raw.groupby('Ticker')['resid'].mean()
between_var = group_means.var()

if total_var > 0:
    lm_stat = (N * T / (2 * (T - 1))) * ((between_var / total_var) ** 2)
    lm_pval = 1 - stats.chi2.cdf(lm_stat, df=1)
else:
    lm_stat, lm_pval = np.nan, np.nan

print('=' * 45)
print('   BREUSCH-PAGAN LM TEST')
print('   (Pooled OLS vs Panel Model)')
print('=' * 45)
print(f'  LM Statistic : {lm_stat:.4f}')
print(f'  p-value      : {lm_pval:.4f}')
print('-' * 45)
if lm_pval < 0.05:
    print('  ✅ Panel effects are significant.')
    print('  Use FE or RE — NOT Pooled OLS.')
else:
    print('  ℹ️  No significant panel effects found.')
    print('  Pooled OLS may be adequate.')
print('=' * 45)

# --- Residual Diagnostic Plots (Fixed Effects) ---
fe_resids = fe_entity_res.resids.values
fe_fitted = fe_entity_res.fitted_values.values

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

axes[0].scatter(fe_fitted, fe_resids, alpha=0.5, color='#2196F3', s=25)
axes[0].axhline(0, color='red', linestyle='--', linewidth=1)
axes[0].set_xlabel('Fitted Values')
axes[0].set_ylabel('Residuals')
axes[0].set_title('Residuals vs Fitted', fontweight='bold')
axes[0].grid(alpha=0.3)

axes[1].hist(fe_resids, bins=25, color='#4CAF50', edgecolor='white', alpha=0.8)
axes[1].set_xlabel('Residuals')
axes[1].set_ylabel('Frequency')
axes[1].set_title('Residual Distribution', fontweight='bold')
axes[1].grid(alpha=0.3)

stats.probplot(fe_resids, dist='norm', plot=axes[2])
axes[2].set_title('Q-Q Plot of Residuals', fontweight='bold')
axes[2].get_lines()[0].set(color='#2196F3', markersize=4, alpha=0.6)
axes[2].get_lines()[1].set(color='red', linewidth=1.5)
axes[2].grid(alpha=0.3)

plt.suptitle('Fixed Effects Model — Residual Diagnostics', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('residual_diagnostics.png', dpi=150, bbox_inches='tight')
plt.show()

# --- Residuals by Stock ---
resid_ticker = fe_entity_res.resids.reset_index()
resid_ticker.columns = ['Ticker', 'Date', 'Residual']

fig, ax = plt.subplots(figsize=(10, 5))
resid_ticker.boxplot(column='Residual', by='Ticker', ax=ax,
                     boxprops=dict(color='#2196F3'),
                     medianprops=dict(color='red', linewidth=2),
                     whiskerprops=dict(color='#2196F3'),
                     capprops=dict(color='#2196F3'),
                     flierprops=dict(marker='o', color='gray', alpha=0.5, markersize=4))
ax.axhline(0, color='red', linestyle='--', alpha=0.5)
ax.set_title('Residuals by Stock — Fixed Effects Model', fontweight='bold')
ax.set_xlabel('Ticker')
ax.set_ylabel('Residual')
plt.suptitle('')
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('residuals_by_stock.png', dpi=150, bbox_inches='tight')
plt.show()

"""##Gráfica de Coeficientes"""

# --- Coefficient Comparison Plot ---
# Handles both linearmodels and statsmodels RE results

def get_coef(res, var):
    """Safely extract coefficient and std error regardless of model type."""
    try:
        # linearmodels result
        if var in res.params.index:
            return res.params[var], res.std_errors[var]
    except:
        pass
    try:
        # statsmodels result (manual RE) — variable name has '_qd' suffix
        var_qd = f'{var}_qd'
        if var_qd in res.params.index:
            return res.params[var_qd], res.bse[var_qd]
    except:
        pass
    return None, None

all_models = {
    'Pooled OLS':     pooled_res,
    'FE (Entity)':    fe_entity_res,
    'FE (Two-Way)':   fe_twoway_res,
    'Random Effects': re_res
}
colors_m = ['#2196F3', '#E91E63', '#4CAF50', '#FF9800']

fig, axes = plt.subplots(1, len(X_vars), figsize=(16, 5))

for ax, var in zip(axes, X_vars):
    coefs, errs, labels, bar_colors = [], [], [], []
    for (name, res), color in zip(all_models.items(), colors_m):
        coef, se = get_coef(res, var)
        if coef is not None:
            coefs.append(coef)
            errs.append(se * 1.96)
            labels.append(name)
            bar_colors.append(color)

    for y, (c, e, color) in enumerate(zip(coefs, errs, bar_colors)):
        ax.barh(y, c, xerr=e, color=color, alpha=0.8, height=0.5,
                error_kw={'elinewidth': 1.5, 'capsize': 4})

    ax.axvline(0, color='black', linewidth=0.8, linestyle='--')
    ax.set_yticks(range(len(labels)))
    ax.set_yticklabels(labels, fontsize=8)
    ax.set_title(var.replace('_lag1', '\n(lag 1)'), fontsize=9, fontweight='bold')
    ax.grid(axis='x', alpha=0.3)

plt.suptitle('Coefficient Comparison Across Models (with 95% CI)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('coefficient_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

"""##Resumen Final del Análisis"""

# --- Final Summary Table ---

def safe_r2(res, kind):
    """Get R² values — works for both linearmodels and statsmodels objects."""
    mapping = {
        'within':  ['rsquared_within',  '_rsquared_within'],
        'between': ['rsquared_between', '_rsquared_between'],
        'overall': ['rsquared_overall', 'rsquared', '_rsquared']
    }
    for attr in mapping.get(kind, []):
        try:
            val = getattr(res, attr)
            if val is not None:
                return f'{float(val):.4f}'
        except:
            continue
    return 'N/A'

def safe_nobs(res):
    for attr in ['nobs', '_nobs', 'df_resid']:
        try:
            return int(getattr(res, attr))
        except:
            continue
    return 'N/A'

rows = []
for name, res in {'Pooled OLS':    pooled_res,
                  'FE (Entity)':   fe_entity_res,
                  'FE (Two-Way)':  fe_twoway_res,
                  'Random Effects': re_res}.items():
    rows.append({
        'Model':        name,
        'R² (Within)':  safe_r2(res, 'within'),
        'R² (Between)': safe_r2(res, 'between'),
        'R² (Overall)': safe_r2(res, 'overall'),
        'N obs':        safe_nobs(res)
    })

summary_df = pd.DataFrame(rows).set_index('Model')

print('=' * 65)
print('         PANEL ANALYSIS — RESULTS SUMMARY')
print('=' * 65)
print(summary_df.to_string())
print()
print('DECISION GUIDE:')
print('  1. Breusch-Pagan p < 0.05 → Panel effects exist → avoid Pooled OLS')
print('  2. Hausman p < 0.05       → Use Fixed Effects')
print('  3. Hausman p ≥ 0.05       → Use Random Effects')
print('  4. R² Within = variation explained within each stock over time')
print('  5. R² Between = variation explained across stocks')
print('=' * 65)

"""# Time Series"""

# ============================================================================
# CELL 8: FORECAST VISUALIZATION (FIXED)
# ============================================================================
print("\n" + "=" * 60)
print("GENERATING FORECAST VISUALIZATION")
print("=" * 60)

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

tickers_list = sorted(df['Ticker'].unique())
forecast_periods_viz = 4

for idx, ticker in enumerate(tickers_list):
    ax = axes[idx]

    ticker_data = df[df['Ticker'] == ticker].sort_values('Date').reset_index(drop=True)

    # Historical data
    ax.plot(ticker_data.index, ticker_data['ROA_TTM'].values, 'b-o', label='Historical', linewidth=2, markersize=6)

    # Add ARIMA forecast if available
    if ticker in arima_results:
        try:
            hist_len = len(ticker_data)
            forecast_vals = arima_results[ticker]['forecast'].values
            forecast_ci = arima_results[ticker]['forecast_ci'].values

            # Ensure we have the right number of forecast periods
            n_forecast = len(forecast_vals)
            forecast_idx = np.arange(hist_len - 1, hist_len - 1 + n_forecast)

            # Plot forecast line
            ax.plot(forecast_idx, forecast_vals, 'r--s', label='ARIMA Forecast', linewidth=2, markersize=6)

            # Plot confidence interval
            if forecast_ci.shape[0] == len(forecast_vals):
                ax.fill_between(forecast_idx, forecast_ci[:, 0], forecast_ci[:, 1], alpha=0.2, color='red')
        except Exception as e:
            print(f"Warning: Could not plot ARIMA forecast for {ticker}: {str(e)}")

    # Add panel AR forecast if available
    if ticker in panel_forecasts:
        try:
            hist_len = len(ticker_data)
            panel_fcst = panel_forecasts[ticker]
            n_forecast = len(panel_fcst)
            forecast_idx = np.arange(hist_len - 1, hist_len - 1 + n_forecast)

            ax.plot(forecast_idx, panel_fcst, 'g--^', label='Panel AR Forecast', linewidth=2, markersize=6)
        except Exception as e:
            print(f"Warning: Could not plot Panel AR forecast for {ticker}: {str(e)}")

    ax.set_title(f'{ticker} - ROA_TTM Forecast', fontsize=12, fontweight='bold')
    ax.set_xlabel('Observation Index')
    ax.set_ylabel('ROA_TTM')
    ax.legend(loc='best', fontsize=9)
    ax.grid(True, alpha=0.3)

# Remove extra subplot if needed
if len(tickers_list) < 6:
    fig.delaxes(axes[5])

plt.tight_layout()
plt.savefig('forecast_comparison.png', dpi=300, bbox_inches='tight')
print("Plot saved as 'forecast_comparison.png'")
plt.show()

print("=" * 60)
print("VISUALIZATION COMPLETE")
print("=" * 60)

"""#Descarga a HTML"""